import React from 'react';

import { ProgressBar } from '../../components/ProgressBar';

import * as S from './styles';

export function Post(){
    return(
        <S.Container>
            <S.Scroll showsVerticalScrollIndicator={false} contentContainerStyle={{paddingTop: 100}}>
            <S.Title>Lorem ipsum</S.Title>

                <S.ContainerContent>
                    <S.Content>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Phasellus laoreet sem non ante faucibus venenatis id non dolor. Nulla pretium laoreet quam, non hendrerit lacus laoreet et. Ut quis tempor metus. Maecenas nisi justo, elementum sed fringilla vitae, tincidunt non magna. Sed posuere egestas egestas. Morbi leo elit, porttitor dapibus mattis sed, ullamcorper nec metus. Vivamus non lectus vel nunc viverra gravida. Praesent cursus magna at porttitor blandit. Aenean auctor neque eget semper elementum. Duis quis justo eu est semper porttitor. Nunc malesuada finibus urna id tristique. Suspendisse potenti. Nulla tempus ut leo quis ullamcorper. Nunc posuere sollicitudin justo, eget luctus ligula laoreet a.
                    </S.Content>
                    <S.Content>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    </S.Content>
                    <S.Content>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Phasellus laoreet sem non ante faucibus venenatis id non dolor. Nulla pretium laoreet quam, non hendrerit lacus laoreet et. Ut quis tempor metus. Maecenas nisi justo, elementum sed fringilla vitae, tincidunt non magna. Sed posuere egestas egestas. Morbi leo elit, porttitor dapibus mattis sed, ullamcorper nec metus. Vivamus non lectus vel nunc viverra gravida. Praesent cursus magna at porttitor blandit. Aenean auctor neque eget semper elementum. Duis quis justo eu est semper porttitor. Nunc malesuada finibus urna id tristique. Suspendisse potenti. Nulla tempus ut leo quis ullamcorper. Nunc posuere sollicitudin justo, eget luctus ligula laoreet a.
                    </S.Content>
                    <S.Content>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id mi eu magna convallis facilisis et eu urna. Morbi a sem et erat molestie facilisis. Pellentesque tortor tortor, ullamcorper ac vulputate vel, condimentum non erat. Donec a massa at magna dictum feugiat. Fusce congue leo id libero feugiat, vehicula faucibus leo interdum. Donec tempor aliquam odio sed lobortis. Sed placerat hendrerit consectetur. Pellentesque pulvinar tortor ac risus sagittis facilisis.
                    Phasellus laoreet sem non ante faucibus venenatis id non dolor. Nulla pretium laoreet quam, non hendrerit lacus laoreet et. Ut quis tempor metus. Maecenas nisi justo, elementum sed fringilla vitae, tincidunt non magna. Sed posuere egestas egestas. Morbi leo elit, porttitor dapibus mattis sed, ullamcorper nec metus. Vivamus non lectus vel nunc viverra gravida. Praesent cursus magna at porttitor blandit. Aenean auctor neque eget semper elementum. Duis quis justo eu est semper porttitor. Nunc malesuada finibus urna id tristique. Suspendisse potenti. Nulla tempus ut leo quis ullamcorper. Nunc posuere sollicitudin justo, eget luctus ligula laoreet a.
                    </S.Content>
                </S.ContainerContent>
            </S.Scroll>

            <ProgressBar value={50} />
        </S.Container>
    )
}